package des.main;

import java.security.InvalidKeyException;
import java.security.NoSuchAlgorithmException;

import javax.crypto.BadPaddingException;
import javax.crypto.Cipher;
import javax.crypto.IllegalBlockSizeException;
import javax.crypto.KeyGenerator;
import javax.crypto.NoSuchPaddingException;
import javax.crypto.SecretKey;

public class des
{
    public static String getDes(String input) throws NoSuchPaddingException, NoSuchAlgorithmException, InvalidKeyException, BadPaddingException, IllegalBlockSizeException {

        KeyGenerator keygenerator = KeyGenerator.getInstance("DES");
        SecretKey myDesKey = keygenerator.generateKey();
        System.out.println("SecretKey: " + myDesKey);
        Cipher desCipher;

        desCipher = Cipher.getInstance("DES/ECB/PKCS5Padding");

        desCipher.init(Cipher.ENCRYPT_MODE, myDesKey);

        byte[]text = "encrypted text".getBytes();

        System.out.println("Text[Byte Format]: " + text);
        System.out.println("Text : " + new String(text));

        byte[]textEncrypted = desCipher.doFinal(text);

        System.out.println("Text Encryted : " + textEncrypted);

        desCipher.init(Cipher.DECRYPT_MODE, myDesKey);
        byte[]textDecrypted = desCipher.doFinal(textEncrypted);

        return new String(textDecrypted);


    }
    public static void main(String[]argv) throws IllegalBlockSizeException, InvalidKeyException, BadPaddingException, NoSuchAlgorithmException, NoSuchPaddingException {
        String s = "13456";
        System.out.println("Your HashCode Generated by DES is: " + getDes(s));
    }
}