package des.main;

import java.io.UnsupportedEncodingException;
import java.math.BigInteger;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;

public class sha1 {

    public static String getSha1(String input) throws UnsupportedEncodingException, NoSuchAlgorithmException {
        MessageDigest digest = MessageDigest.getInstance("SHA-1");
        digest.reset();
        digest.update(input.getBytes("utf8"));
        input = String.format("%040x", new BigInteger(1, digest.digest()));
        return input;
    }

    public static void main(String[] argv) throws UnsupportedEncodingException, NoSuchAlgorithmException {
        String value = "123456";
        System.out.println("HashCode Generated by SHA-1 for:");
        System.out.println("\n" + value + " : " + getSha1(value));

    }
}